plugins {
    id 'net.fabricmc.fabric-loom' version '1.17-SNAPSHOT'
}

version = project.mod_version
group = 'net.raphimc.viabedrock'

base {
    archivesName = 'viabedrock-data-generator'
}

dependencies {
    minecraft "com.mojang:minecraft:${project.minecraft_version}"
    implementation "net.fabricmc:fabric-loader:${project.loader_version}"
}

tasks.withType(JavaCompile).configureEach {
    options.release = 25
}

processResources {
    inputs.property 'version', project.version
    filesMatching('fabric.mod.json') {
        expand version: project.version
    }
}

java {
    sourceCompatibility = JavaVersion.VERSION_25
    targetCompatibility = JavaVersion.VERSION_25
}

jar {
    from('../LICENSE')
}
