version: 2
registries:
  maven-central:
    type: maven-repository
    url: "https://repo1.maven.org/maven2/"
updates:
  - package-ecosystem: "gradle"
    directory: "/"
    schedule:
      interval: "daily"
    registries:
      - maven-central
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
